#  ======================================================================
#                               __
#       ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿    / _\_ __   __ ___      ___ __   ___ _ __
#      ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠁⠈⠉⢙⣿⣿⣿⣿⣿⣿   \ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__|
#     ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠋   ⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿  _\ \ |_) | (_| |\ V  V /| | | |  __/ |
#     ⣿⣿⣿⣿⣿⣿⣿⣿⣿    ⢠⣿⣿⣿⣿⠋⠉⠉⢿⣿⣿  \__/ .__/ \__,_| \_/\_/ |_| |_|\___|_|
#     ⣿⣿⣿⣿⣿⣿⣿⣿⣿⠂    ⠈⠋⠋⠁   ⣾⣿⣿     |_|
#     ⣿⣿⣿⣿⣿⣿⣿⠋⠁         ⢀⣴⣾⣿⣿⣿     ___            _             _
#     ⣿⣿⣿⣿⣿⠋⠁     ⢀⣤⣤⣤⣤⣴⣾⣿⣿⣿⣿⣿    / __\___  _ __ | |_ _ __ ___ | |
#     ⣿⣿⣏⠋⢀⣀    ⢠⣦⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   / /  / _ \| '_ \| __| '__/ _ \| |
#      ⣿⣗ ⣿⣿⠗ ⣠⣦⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   / /__| (_) | | | | |_| | | (_) | |
#       ⣿⣦⣤⣤⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿    \____/\___/|_| |_|\__|_|  \___/|_|
#
#  ======================================================================

# To completely disable SpawnerControl functionality, change this to 'false'.
enable-spawner-control: true


# Establish what worlds and mobs SpawnerControl will be allowed to work on.
allowed-worlds:
  allowed-list: ['world'] # For all worlds, use '*'.
  excluded-list: ['']

allowed-entity-types:
  allowed-list: ['slime'] # For all mobs, use '*'.
  excluded-list: ['']

use-spawn-types: ['CHICKEN', 'COW']

# Establish the minimum and maximum light level required for the spawner to activate.
# By default, we use all light levels.
#  0 = No Light Source
# 15 = Brightest Light Source
allowed-light-levels: 0-15

# Other optional light criteria - Get the amount of light at this block from the sky.
# Any light given from other sources (such as blocks like torches) will be ignored.
allowed-skylight-levels: 0-15

# Other optional light criteria - Get the amount of light at this block from nearby blocks.
# Any light given from other sources (such as the sun) will be ignored.
allowed-block-light-levels: 0-15

# Establish the activation range of spawners when a player is nearby, measured in blocks.
player-required-range: 6


# Establish the minimum and maximum spawn delay, measured in ticks.
min-spawn-delay: 200
max-spawn-delay: 800


# Establish the maximum number of mobs of the same type within the range of the spawner.
max-nearby-entities: 4


# Establish the maximum number of mobs which will attempt to spawn during each spawn event.
# Can be a number or a number range
spawn-count: 1-2


# Establish the maximum number of blocks from the spawner a mob will attempt to spawn during each spawn event.
spawn-range: 6


# Establishes the spawner cube delay, measured in ticks.
spawner-delay: 20


# When set to 'false', mobs will only attempt to spawn on solid ground, rather than in the air.
allow-air-spawning: false

# If set to true, the first time a spawner is activated by a player, it triggers a mob spawn immediately
immediate-spawn: false

# If set to 0, the immiate-spawn will only happen once, otherwise it will reset after the specified number of ticks
immediate-spawn-reset-period: 0

command-to-run: ''
also-spawn-mob: true
create-particles-on-spawner: true


# Optional and requires NBTAPI - https://www.spigotmc.org/resources/nbt-api.7939/
nbt-data: ''

# Spawners with the group group id will all spawn at the same time when one of them is triggered
spawn-group-id: ''

# Unused Settings

# Establish Slime-Specific modifications
# slime-size-min: 1
# slime-size-max: 4


# Establish WorldGuard Region Exceptions
worldguard-regions:
#  - region_1:
#    player-required-range: 100
#    slime-size-min: 1
#    slime-size-max: 1
#    spawn-range: 6
#    min-spawn-delay: 20
#    max-spawn-delay: 40

#    allowed-entity-types:
#      allowed-list: ['zombie', 'slime']


# Establish Identified Spawner Exceptions
named-spawners:
#  - name_1:
#    allowed-entity-types:
#      allowed-list: ['husk']