package me.stumper66.spawnercontrol;

public enum DebugTypes {
    ACTIVE_SPAWNERS,
    CHUNK_LOAD,
    ENTITY_SPECIFIC,
    PLAYER_ACTIVATION,
    SPAWN_ATTEMPT_FAILED,
    SPAWN_ATTEMPT_SUCCESS,
    SPAWNER_DEACTIVATION,
    SPAWNER_ACTIVATION
}
