package me.stumper66.spawnercontrol;

public enum DebugType {
    ACTIVE_SPAWNERS,
    CHUNK_LOAD,
    ENTITY_SPECIFIC,
    LIGHT_REQ_NOT_MET,
    PLAYER_ACTIVATION,
    SPAWN_ATTEMPT_FAILED,
    SPAWN_ATTEMPT_SUCCESS,
    SPAWNER_DEACTIVATION,
    SPAWNER_ACTIVATION,
    TICKS_LEFT
}
